"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import { usePathname } from 'next/navigation'
import Navbar from '../components/Navbar'
import NavbarAdmin from '../components/NavbarAdmin'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

const disable = ["/login"]

// export const metadata = {
//   title: 'NOC APP',
//   description: 'Generated by ilkom21',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        {pathname === "/Dashboard" || pathname === "/Wilayah" ? <NavbarAdmin/> : !disable.includes(pathname) && <Navbar/>}
        <div className='overflow-x-hidden'>
          {children}
        </div>
        {/* {!disable.includes(pathname) && <Footer/>} */}
      </body>
    </html>
  )
}
